//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ListTicketsParamsStatus.
const (
	Closed  ListTicketsParamsStatus = "closed"
	Hold    ListTicketsParamsStatus = "hold"
	New     ListTicketsParamsStatus = "new"
	Open    ListTicketsParamsStatus = "open"
	Pending ListTicketsParamsStatus = "pending"
	Solved  ListTicketsParamsStatus = "solved"
)

// Valid indicates whether the value is a known member of the ListTicketsParamsStatus enum.
func (e ListTicketsParamsStatus) Valid() bool {
	switch e {
	case Closed:
		return true
	case Hold:
		return true
	case New:
		return true
	case Open:
		return true
	case Pending:
		return true
	case Solved:
		return true
	default:
		return false
	}
}

// Defines values for ListTicketsParamsType.
const (
	Incident ListTicketsParamsType = "incident"
	Problem  ListTicketsParamsType = "problem"
	Question ListTicketsParamsType = "question"
	Task     ListTicketsParamsType = "task"
)

// Valid indicates whether the value is a known member of the ListTicketsParamsType enum.
func (e ListTicketsParamsType) Valid() bool {
	switch e {
	case Incident:
		return true
	case Problem:
		return true
	case Question:
		return true
	case Task:
		return true
	default:
		return false
	}
}

// Defines values for ListTicketsParamsPriority.
const (
	High   ListTicketsParamsPriority = "high"
	Low    ListTicketsParamsPriority = "low"
	Normal ListTicketsParamsPriority = "normal"
	Urgent ListTicketsParamsPriority = "urgent"
)

// Valid indicates whether the value is a known member of the ListTicketsParamsPriority enum.
func (e ListTicketsParamsPriority) Valid() bool {
	switch e {
	case High:
		return true
	case Low:
		return true
	case Normal:
		return true
	case Urgent:
		return true
	default:
		return false
	}
}

// Defines values for ListTicketsParamsSortBy.
const (
	CreatedAt ListTicketsParamsSortBy = "created_at"
	UpdatedAt ListTicketsParamsSortBy = "updated_at"
)

// Valid indicates whether the value is a known member of the ListTicketsParamsSortBy enum.
func (e ListTicketsParamsSortBy) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case UpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListTicketsParamsSortOrder.
const (
	Asc  ListTicketsParamsSortOrder = "asc"
	Desc ListTicketsParamsSortOrder = "desc"
)

// Valid indicates whether the value is a known member of the ListTicketsParamsSortOrder enum.
func (e ListTicketsParamsSortOrder) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// SatisfactionRating defines model for SatisfactionRating.
type SatisfactionRating struct {
	Comment  *string `json:"comment,omitempty"`
	Id       *int64  `json:"id,omitempty"`
	Reason   *string `json:"reason,omitempty"`
	ReasonId *int64  `json:"reason_id,omitempty"`
	Score    *string `json:"score,omitempty"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	AllowAttachments *bool      `json:"allow_attachments,omitempty"`
	AllowChannelback *bool      `json:"allow_channelback,omitempty"`
	AssigneeId       *int64     `json:"assignee_id,omitempty"`
	BrandId          *int64     `json:"brand_id,omitempty"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`

	// CustomFields Custom field values
	CustomFields         interface{}         `json:"custom_fields,omitempty"`
	CustomStatusId       *int64              `json:"custom_status_id,omitempty"`
	Description          *string             `json:"description,omitempty"`
	ExternalId           *string             `json:"external_id,omitempty"`
	FromMessagingChannel *bool               `json:"from_messaging_channel,omitempty"`
	GroupId              *int64              `json:"group_id,omitempty"`
	HasIncidents         *bool               `json:"has_incidents,omitempty"`
	Id                   int64               `json:"id"`
	IsPublic             *bool               `json:"is_public,omitempty"`
	OrganizationId       *int64              `json:"organization_id,omitempty"`
	Priority             *string             `json:"priority,omitempty"`
	RawSubject           *string             `json:"raw_subject,omitempty"`
	Recipient            *string             `json:"recipient,omitempty"`
	RequesterId          *int64              `json:"requester_id,omitempty"`
	SatisfactionRating   *SatisfactionRating `json:"satisfaction_rating,omitempty"`
	Status               *string             `json:"status,omitempty"`
	Subject              *string             `json:"subject,omitempty"`
	SubmitterId          *int64              `json:"submitter_id,omitempty"`

	// Tags Raw tags string
	Tags         *string    `json:"tags,omitempty"`
	TicketFormId *int64     `json:"ticket_form_id,omitempty"`
	Type         *string    `json:"type,omitempty"`
	UpdatedAt    *time.Time `json:"updated_at,omitempty"`
	Url          *string    `json:"url,omitempty"`
	Via          *Via       `json:"via,omitempty"`
}

// TicketDetail defines model for TicketDetail.
type TicketDetail struct {
	AllowAttachments *bool      `json:"allow_attachments,omitempty"`
	AllowChannelback *bool      `json:"allow_channelback,omitempty"`
	AssigneeId       *int64     `json:"assignee_id,omitempty"`
	BrandId          *int64     `json:"brand_id,omitempty"`
	CollaboratorIds  *[]int64   `json:"collaborator_ids,omitempty"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`

	// CustomFields Custom field values
	CustomFields         interface{}         `json:"custom_fields,omitempty"`
	CustomStatusId       *int64              `json:"custom_status_id,omitempty"`
	Description          *string             `json:"description,omitempty"`
	EmailCcIds           *[]int64            `json:"email_cc_ids,omitempty"`
	ExternalId           *string             `json:"external_id,omitempty"`
	FollowerIds          *[]int64            `json:"follower_ids,omitempty"`
	FollowupIds          *[]int64            `json:"followup_ids,omitempty"`
	FromMessagingChannel *bool               `json:"from_messaging_channel,omitempty"`
	GroupId              *int64              `json:"group_id,omitempty"`
	HasIncidents         *bool               `json:"has_incidents,omitempty"`
	Id                   int64               `json:"id"`
	IsPublic             *bool               `json:"is_public,omitempty"`
	OrganizationId       *int64              `json:"organization_id,omitempty"`
	Priority             *string             `json:"priority,omitempty"`
	RawSubject           *string             `json:"raw_subject,omitempty"`
	Recipient            *string             `json:"recipient,omitempty"`
	RequesterId          *int64              `json:"requester_id,omitempty"`
	SatisfactionRating   *SatisfactionRating `json:"satisfaction_rating,omitempty"`
	Status               *string             `json:"status,omitempty"`
	Subject              *string             `json:"subject,omitempty"`
	SubmitterId          *int64              `json:"submitter_id,omitempty"`
	TagList              *[]string           `json:"tag_list,omitempty"`

	// Tags Raw tags string
	Tags         *string    `json:"tags,omitempty"`
	TicketFormId *int64     `json:"ticket_form_id,omitempty"`
	Type         *string    `json:"type,omitempty"`
	UpdatedAt    *time.Time `json:"updated_at,omitempty"`
	Url          *string    `json:"url,omitempty"`
	Via          *Via       `json:"via,omitempty"`
}

// TicketList defines model for TicketList.
type TicketList struct {
	Limit   int      `json:"limit"`
	Offset  int      `json:"offset"`
	Tickets []Ticket `json:"tickets"`
	Total   int64    `json:"total"`
}

// Via defines model for Via.
type Via struct {
	Channel *string `json:"channel,omitempty"`

	// SourceFrom Source origin details
	SourceFrom interface{} `json:"source_from,omitempty"`
	SourceRel  *string     `json:"source_rel,omitempty"`

	// SourceTo Source destination details
	SourceTo interface{} `json:"source_to,omitempty"`
}

// ListTicketsParams defines parameters for ListTickets.
type ListTicketsParams struct {
	Status         *ListTicketsParamsStatus   `form:"status,omitempty" json:"status,omitempty"`
	Type           *ListTicketsParamsType     `form:"type,omitempty" json:"type,omitempty"`
	Priority       *ListTicketsParamsPriority `form:"priority,omitempty" json:"priority,omitempty"`
	RequesterId    *int64                     `form:"requester_id,omitempty" json:"requester_id,omitempty"`
	AssigneeId     *int64                     `form:"assignee_id,omitempty" json:"assignee_id,omitempty"`
	SubmitterId    *int64                     `form:"submitter_id,omitempty" json:"submitter_id,omitempty"`
	OrganizationId *int64                     `form:"organization_id,omitempty" json:"organization_id,omitempty"`
	GroupId        *int64                     `form:"group_id,omitempty" json:"group_id,omitempty"`
	BrandId        *int64                     `form:"brand_id,omitempty" json:"brand_id,omitempty"`

	// Tag Filter by tag value
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`

	// Search Search in subject (case-insensitive)
	Search        *string                     `form:"search,omitempty" json:"search,omitempty"`
	CreatedAfter  *time.Time                  `form:"created_after,omitempty" json:"created_after,omitempty"`
	CreatedBefore *time.Time                  `form:"created_before,omitempty" json:"created_before,omitempty"`
	Limit         *int                        `form:"limit,omitempty" json:"limit,omitempty"`
	Offset        *int                        `form:"offset,omitempty" json:"offset,omitempty"`
	SortBy        *ListTicketsParamsSortBy    `form:"sort_by,omitempty" json:"sort_by,omitempty"`
	SortOrder     *ListTicketsParamsSortOrder `form:"sort_order,omitempty" json:"sort_order,omitempty"`
}

// ListTicketsParamsStatus defines parameters for ListTickets.
type ListTicketsParamsStatus string

// ListTicketsParamsType defines parameters for ListTickets.
type ListTicketsParamsType string

// ListTicketsParamsPriority defines parameters for ListTickets.
type ListTicketsParamsPriority string

// ListTicketsParamsSortBy defines parameters for ListTickets.
type ListTicketsParamsSortBy string

// ListTicketsParamsSortOrder defines parameters for ListTickets.
type ListTicketsParamsSortOrder string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List tickets with optional filters and pagination
	// (GET /v1/tickets)
	ListTickets(w http.ResponseWriter, r *http.Request, params ListTicketsParams)
	// Get a single ticket with all related data
	// (GET /v1/tickets/{ticketId})
	GetTicket(w http.ResponseWriter, r *http.Request, ticketId int64)
	// Get collaborator IDs for a ticket
	// (GET /v1/tickets/{ticketId}/collaborators)
	GetTicketCollaborators(w http.ResponseWriter, r *http.Request, ticketId int64)
	// Get email CC user IDs for a ticket
	// (GET /v1/tickets/{ticketId}/email-ccs)
	GetTicketEmailCCs(w http.ResponseWriter, r *http.Request, ticketId int64)
	// Get follower IDs for a ticket
	// (GET /v1/tickets/{ticketId}/followers)
	GetTicketFollowers(w http.ResponseWriter, r *http.Request, ticketId int64)
	// Get follow-up ticket IDs
	// (GET /v1/tickets/{ticketId}/followups)
	GetTicketFollowups(w http.ResponseWriter, r *http.Request, ticketId int64)
	// Get tags for a ticket
	// (GET /v1/tickets/{ticketId}/tags)
	GetTicketTags(w http.ResponseWriter, r *http.Request, ticketId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListTickets operation middleware
func (siw *ServerInterfaceWrapper) ListTickets(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTicketsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	// ------------- Optional query parameter "priority" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "priority", r.URL.Query(), &params.Priority, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "priority", Err: err})
		return
	}

	// ------------- Optional query parameter "requester_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "requester_id", r.URL.Query(), &params.RequesterId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "requester_id", Err: err})
		return
	}

	// ------------- Optional query parameter "assignee_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "assignee_id", r.URL.Query(), &params.AssigneeId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assignee_id", Err: err})
		return
	}

	// ------------- Optional query parameter "submitter_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "submitter_id", r.URL.Query(), &params.SubmitterId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "submitter_id", Err: err})
		return
	}

	// ------------- Optional query parameter "organization_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "organization_id", r.URL.Query(), &params.OrganizationId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organization_id", Err: err})
		return
	}

	// ------------- Optional query parameter "group_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group_id", r.URL.Query(), &params.GroupId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_id", Err: err})
		return
	}

	// ------------- Optional query parameter "brand_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "brand_id", r.URL.Query(), &params.BrandId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "brand_id", Err: err})
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", r.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	// ------------- Optional query parameter "created_after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_after", r.URL.Query(), &params.CreatedAfter, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_after", Err: err})
		return
	}

	// ------------- Optional query parameter "created_before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_before", r.URL.Query(), &params.CreatedBefore, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_before", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_by", r.URL.Query(), &params.SortBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_by", Err: err})
		return
	}

	// ------------- Optional query parameter "sort_order" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort_order", r.URL.Query(), &params.SortOrder, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort_order", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTickets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicket operation middleware
func (siw *ServerInterfaceWrapper) GetTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ticketId" -------------
	var ticketId int64

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", r.PathValue("ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicket(w, r, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicketCollaborators operation middleware
func (siw *ServerInterfaceWrapper) GetTicketCollaborators(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ticketId" -------------
	var ticketId int64

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", r.PathValue("ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicketCollaborators(w, r, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicketEmailCCs operation middleware
func (siw *ServerInterfaceWrapper) GetTicketEmailCCs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ticketId" -------------
	var ticketId int64

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", r.PathValue("ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicketEmailCCs(w, r, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicketFollowers operation middleware
func (siw *ServerInterfaceWrapper) GetTicketFollowers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ticketId" -------------
	var ticketId int64

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", r.PathValue("ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicketFollowers(w, r, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicketFollowups operation middleware
func (siw *ServerInterfaceWrapper) GetTicketFollowups(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ticketId" -------------
	var ticketId int64

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", r.PathValue("ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicketFollowups(w, r, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicketTags operation middleware
func (siw *ServerInterfaceWrapper) GetTicketTags(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "ticketId" -------------
	var ticketId int64

	err = runtime.BindStyledParameterWithOptions("simple", "ticketId", r.PathValue("ticketId"), &ticketId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ticketId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicketTags(w, r, ticketId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/v1/tickets", wrapper.ListTickets)
	m.HandleFunc("GET "+options.BaseURL+"/v1/tickets/{ticketId}", wrapper.GetTicket)
	m.HandleFunc("GET "+options.BaseURL+"/v1/tickets/{ticketId}/collaborators", wrapper.GetTicketCollaborators)
	m.HandleFunc("GET "+options.BaseURL+"/v1/tickets/{ticketId}/email-ccs", wrapper.GetTicketEmailCCs)
	m.HandleFunc("GET "+options.BaseURL+"/v1/tickets/{ticketId}/followers", wrapper.GetTicketFollowers)
	m.HandleFunc("GET "+options.BaseURL+"/v1/tickets/{ticketId}/followups", wrapper.GetTicketFollowups)
	m.HandleFunc("GET "+options.BaseURL+"/v1/tickets/{ticketId}/tags", wrapper.GetTicketTags)

	return m
}
