// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGroups = `-- name: CountGroups :one
SELECT count(*) FROM zendesk.groups
`

func (q *Queries) CountGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, description, is_public, "default", deleted, created_at, updated_at, _dlt_load_id, _dlt_id FROM zendesk.groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id int64) (ZendeskGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i ZendeskGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPublic,
		&i.Default,
		&i.Deleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DltLoadID,
		&i.DltID,
	)
	return i, err
}

const getGroupNames = `-- name: GetGroupNames :many
SELECT id, name FROM zendesk.groups WHERE id = ANY($1::bigint[])
`

type GetGroupNamesRow struct {
	ID   int64
	Name pgtype.Text
}

func (q *Queries) GetGroupNames(ctx context.Context, ids []int64) ([]GetGroupNamesRow, error) {
	rows, err := q.db.Query(ctx, getGroupNames, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupNamesRow
	for rows.Next() {
		var i GetGroupNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, description, is_public, "default", deleted, created_at, updated_at, _dlt_load_id, _dlt_id FROM zendesk.groups
ORDER BY name ASC
LIMIT $2 OFFSET $1
`

type ListGroupsParams struct {
	QueryOffset int32
	QueryLimit  int32
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]ZendeskGroup, error) {
	rows, err := q.db.Query(ctx, listGroups, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZendeskGroup
	for rows.Next() {
		var i ZendeskGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPublic,
			&i.Default,
			&i.Deleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DltLoadID,
			&i.DltID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
