// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ZendeskTicket struct {
	ID                         int64
	Subject                    pgtype.Text
	RawSubject                 pgtype.Text
	Description                pgtype.Text
	Status                     pgtype.Text
	Type                       pgtype.Text
	Priority                   pgtype.Text
	Recipient                  pgtype.Text
	RequesterID                pgtype.Int8
	SubmitterID                pgtype.Int8
	AssigneeID                 pgtype.Int8
	OrganizationID             pgtype.Int8
	GroupID                    pgtype.Int8
	BrandID                    pgtype.Int8
	TicketFormID               pgtype.Int8
	CustomStatusID             pgtype.Int8
	ExternalID                 pgtype.Text
	Url                        pgtype.Text
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	GeneratedTimestamp         pgtype.Int8
	HasIncidents               pgtype.Bool
	IsPublic                   pgtype.Bool
	AllowChannelback           pgtype.Bool
	AllowAttachments           pgtype.Bool
	FromMessagingChannel       pgtype.Bool
	Tags                       pgtype.Text
	CustomFields               []byte
	SatisfactionRatingScore    pgtype.Text
	SatisfactionRatingID       pgtype.Int8
	SatisfactionRatingReason   pgtype.Text
	SatisfactionRatingReasonID pgtype.Int8
	SatisfactionRatingComment  pgtype.Text
	ViaChannel                 pgtype.Text
	ViaSourceFrom              []byte
	ViaSourceTo                []byte
	ViaSourceRel               pgtype.Text
	DltLoadID                  pgtype.Text
	DltID                      string
}

type ZendeskTicketsCollaboratorID struct {
	Value       pgtype.Int8
	DltRootID   pgtype.Text
	DltParentID pgtype.Text
	DltListIdx  pgtype.Int8
	DltID       string
}

type ZendeskTicketsEmailCcID struct {
	Value       pgtype.Int8
	DltRootID   pgtype.Text
	DltParentID pgtype.Text
	DltListIdx  pgtype.Int8
	DltID       string
}

type ZendeskTicketsFollowerID struct {
	Value       pgtype.Int8
	DltRootID   pgtype.Text
	DltParentID pgtype.Text
	DltListIdx  pgtype.Int8
	DltID       string
}

type ZendeskTicketsFollowupID struct {
	Value       pgtype.Int8
	DltRootID   pgtype.Text
	DltParentID pgtype.Text
	DltListIdx  pgtype.Int8
	DltID       string
}

type ZendeskTicketsTag struct {
	Value       pgtype.Text
	DltRootID   pgtype.Text
	DltParentID pgtype.Text
	DltListIdx  pgtype.Int8
	DltID       string
}
