// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ZendeskGroup struct {
	ID          int64
	Name        pgtype.Text
	Description pgtype.Text
	IsPublic    pgtype.Bool
	Default     pgtype.Bool
	Deleted     pgtype.Bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DltLoadID   pgtype.Text
	DltID       string
}

type ZendeskOrganization struct {
	ID             int64
	Name           pgtype.Text
	SharedTickets  pgtype.Bool
	SharedComments pgtype.Bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Details        pgtype.Text
	Notes          pgtype.Text
	GroupID        pgtype.Int8
	DltLoadID      pgtype.Text
	DltID          string
}

type ZendeskTicket struct {
	ID                         int64
	Subject                    pgtype.Text
	RawSubject                 pgtype.Text
	Description                pgtype.Text
	Status                     pgtype.Text
	Type                       pgtype.Text
	Priority                   pgtype.Text
	Recipient                  pgtype.Text
	RequesterID                pgtype.Int8
	SubmitterID                pgtype.Int8
	AssigneeID                 pgtype.Int8
	OrganizationID             pgtype.Int8
	GroupID                    pgtype.Int8
	BrandID                    pgtype.Int8
	TicketFormID               pgtype.Int8
	CustomStatusID             pgtype.Int8
	ExternalID                 pgtype.Text
	Url                        pgtype.Text
	CreatedAt                  pgtype.Timestamptz
	UpdatedAt                  pgtype.Timestamptz
	GeneratedTimestamp         pgtype.Int8
	HasIncidents               pgtype.Bool
	IsPublic                   pgtype.Bool
	AllowChannelback           pgtype.Bool
	AllowAttachments           pgtype.Bool
	FromMessagingChannel       pgtype.Bool
	Tags                       pgtype.Text
	CustomFields               []byte
	SatisfactionRatingScore    pgtype.Text
	SatisfactionRatingID       pgtype.Int8
	SatisfactionRatingReason   pgtype.Text
	SatisfactionRatingReasonID pgtype.Int8
	SatisfactionRatingComment  pgtype.Text
	ViaChannel                 pgtype.Text
	ViaSourceFrom              []byte
	ViaSourceTo                []byte
	ViaSourceRel               pgtype.Text
	DltLoadID                  pgtype.Text
	DltID                      string
}

type ZendeskTicketComment struct {
	ID         int64
	Type       pgtype.Text
	AuthorID   pgtype.Int8
	Body       pgtype.Text
	HtmlBody   pgtype.Text
	PlainBody  pgtype.Text
	Public     pgtype.Bool
	AuditID    pgtype.Int8
	CreatedAt  pgtype.Timestamptz
	TicketID   pgtype.Int8
	ViaChannel pgtype.Text
	DltLoadID  string
	DltID      string
}

type ZendeskTicketsCollaboratorID struct {
	Value       pgtype.Int8
	DltRootID   pgtype.Text
	DltParentID pgtype.Text
	DltListIdx  pgtype.Int8
	DltID       string
}

type ZendeskTicketsEmailCcID struct {
	Value       pgtype.Int8
	DltRootID   pgtype.Text
	DltParentID pgtype.Text
	DltListIdx  pgtype.Int8
	DltID       string
}

type ZendeskTicketsFollowerID struct {
	Value       pgtype.Int8
	DltRootID   pgtype.Text
	DltParentID pgtype.Text
	DltListIdx  pgtype.Int8
	DltID       string
}

type ZendeskTicketsFollowupID struct {
	Value       pgtype.Int8
	DltRootID   pgtype.Text
	DltParentID pgtype.Text
	DltListIdx  pgtype.Int8
	DltID       string
}

type ZendeskTicketsTag struct {
	Value       pgtype.Text
	DltRootID   pgtype.Text
	DltParentID pgtype.Text
	DltListIdx  pgtype.Int8
	DltID       string
}

type ZendeskUser struct {
	ID             int64
	Name           pgtype.Text
	Email          pgtype.Text
	Role           pgtype.Text
	OrganizationID pgtype.Int8
	Active         pgtype.Bool
	Suspended      pgtype.Bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	TimeZone       pgtype.Text
	Locale         pgtype.Text
	Phone          pgtype.Text
	DltLoadID      pgtype.Text
	DltID          string
}
