// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizations = `-- name: CountOrganizations :one
SELECT count(*) FROM zendesk.organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, shared_tickets, shared_comments, created_at, updated_at, details, notes, group_id, _dlt_load_id, _dlt_id FROM zendesk.organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id int64) (ZendeskOrganization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i ZendeskOrganization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SharedTickets,
		&i.SharedComments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Details,
		&i.Notes,
		&i.GroupID,
		&i.DltLoadID,
		&i.DltID,
	)
	return i, err
}

const getOrganizationNames = `-- name: GetOrganizationNames :many
SELECT id, name FROM zendesk.organizations WHERE id = ANY($1::bigint[])
`

type GetOrganizationNamesRow struct {
	ID   int64
	Name pgtype.Text
}

func (q *Queries) GetOrganizationNames(ctx context.Context, ids []int64) ([]GetOrganizationNamesRow, error) {
	rows, err := q.db.Query(ctx, getOrganizationNames, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrganizationNamesRow
	for rows.Next() {
		var i GetOrganizationNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, shared_tickets, shared_comments, created_at, updated_at, details, notes, group_id, _dlt_load_id, _dlt_id FROM zendesk.organizations
ORDER BY name ASC
LIMIT $2 OFFSET $1
`

type ListOrganizationsParams struct {
	QueryOffset int32
	QueryLimit  int32
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]ZendeskOrganization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZendeskOrganization
	for rows.Next() {
		var i ZendeskOrganization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SharedTickets,
			&i.SharedComments,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Details,
			&i.Notes,
			&i.GroupID,
			&i.DltLoadID,
			&i.DltID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
