// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTickets = `-- name: CountTickets :one
SELECT count(*) FROM zendesk.tickets t
WHERE
    ($1::varchar IS NULL OR t.status = $1) AND
    ($2::varchar IS NULL OR t.type = $2) AND
    ($3::varchar IS NULL OR t.priority = $3) AND
    ($4::bigint IS NULL OR t.requester_id = $4) AND
    ($5::bigint IS NULL OR t.assignee_id = $5) AND
    ($6::bigint IS NULL OR t.submitter_id = $6) AND
    ($7::bigint IS NULL OR t.organization_id = $7) AND
    ($8::bigint IS NULL OR t.group_id = $8) AND
    ($9::bigint IS NULL OR t.brand_id = $9) AND
    ($10::varchar IS NULL OR t.subject ILIKE '%' || $10 || '%') AND
    ($11::timestamptz IS NULL OR t.created_at >= $11) AND
    ($12::timestamptz IS NULL OR t.created_at <= $12) AND
    ($13::varchar IS NULL OR EXISTS (
        SELECT 1 FROM zendesk.tickets__tags tag
        WHERE tag._dlt_root_id = t._dlt_id AND tag.value = $13
    ))
`

type CountTicketsParams struct {
	Status         pgtype.Text
	TicketType     pgtype.Text
	Priority       pgtype.Text
	RequesterID    pgtype.Int8
	AssigneeID     pgtype.Int8
	SubmitterID    pgtype.Int8
	OrganizationID pgtype.Int8
	GroupID        pgtype.Int8
	BrandID        pgtype.Int8
	Search         pgtype.Text
	CreatedAfter   pgtype.Timestamptz
	CreatedBefore  pgtype.Timestamptz
	Tag            pgtype.Text
}

func (q *Queries) CountTickets(ctx context.Context, arg CountTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTickets,
		arg.Status,
		arg.TicketType,
		arg.Priority,
		arg.RequesterID,
		arg.AssigneeID,
		arg.SubmitterID,
		arg.OrganizationID,
		arg.GroupID,
		arg.BrandID,
		arg.Search,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.Tag,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, subject, raw_subject, description, status, type, priority, recipient, requester_id, submitter_id, assignee_id, organization_id, group_id, brand_id, ticket_form_id, custom_status_id, external_id, url, created_at, updated_at, generated_timestamp, has_incidents, is_public, allow_channelback, allow_attachments, from_messaging_channel, tags, custom_fields, satisfaction_rating__score, satisfaction_rating__id, satisfaction_rating__reason, satisfaction_rating__reason_id, satisfaction_rating__comment, via__channel, via__source__from, via__source__to, via__source__rel, _dlt_load_id, _dlt_id FROM zendesk.tickets WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id int64) (ZendeskTicket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i ZendeskTicket
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.RawSubject,
		&i.Description,
		&i.Status,
		&i.Type,
		&i.Priority,
		&i.Recipient,
		&i.RequesterID,
		&i.SubmitterID,
		&i.AssigneeID,
		&i.OrganizationID,
		&i.GroupID,
		&i.BrandID,
		&i.TicketFormID,
		&i.CustomStatusID,
		&i.ExternalID,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GeneratedTimestamp,
		&i.HasIncidents,
		&i.IsPublic,
		&i.AllowChannelback,
		&i.AllowAttachments,
		&i.FromMessagingChannel,
		&i.Tags,
		&i.CustomFields,
		&i.SatisfactionRatingScore,
		&i.SatisfactionRatingID,
		&i.SatisfactionRatingReason,
		&i.SatisfactionRatingReasonID,
		&i.SatisfactionRatingComment,
		&i.ViaChannel,
		&i.ViaSourceFrom,
		&i.ViaSourceTo,
		&i.ViaSourceRel,
		&i.DltLoadID,
		&i.DltID,
	)
	return i, err
}

const getTicketCollaborators = `-- name: GetTicketCollaborators :many
SELECT c.value FROM zendesk.tickets__collaborator_ids c
JOIN zendesk.tickets t ON c._dlt_root_id = t._dlt_id
WHERE t.id = $1
ORDER BY c._dlt_list_idx
`

func (q *Queries) GetTicketCollaborators(ctx context.Context, id int64) ([]pgtype.Int8, error) {
	rows, err := q.db.Query(ctx, getTicketCollaborators, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Int8
	for rows.Next() {
		var value pgtype.Int8
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketComments = `-- name: GetTicketComments :many
SELECT id, type, author_id, plain_body, public, created_at, via__channel
FROM zendesk.ticket_comments
WHERE ticket_id = $1
ORDER BY created_at ASC
`

type GetTicketCommentsRow struct {
	ID         int64
	Type       pgtype.Text
	AuthorID   pgtype.Int8
	PlainBody  pgtype.Text
	Public     pgtype.Bool
	CreatedAt  pgtype.Timestamptz
	ViaChannel pgtype.Text
}

func (q *Queries) GetTicketComments(ctx context.Context, ticketID pgtype.Int8) ([]GetTicketCommentsRow, error) {
	rows, err := q.db.Query(ctx, getTicketComments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTicketCommentsRow
	for rows.Next() {
		var i GetTicketCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AuthorID,
			&i.PlainBody,
			&i.Public,
			&i.CreatedAt,
			&i.ViaChannel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketEmailCCs = `-- name: GetTicketEmailCCs :many
SELECT e.value FROM zendesk.tickets__email_cc_ids e
JOIN zendesk.tickets t ON e._dlt_root_id = t._dlt_id
WHERE t.id = $1
ORDER BY e._dlt_list_idx
`

func (q *Queries) GetTicketEmailCCs(ctx context.Context, id int64) ([]pgtype.Int8, error) {
	rows, err := q.db.Query(ctx, getTicketEmailCCs, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Int8
	for rows.Next() {
		var value pgtype.Int8
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketFollowers = `-- name: GetTicketFollowers :many
SELECT f.value FROM zendesk.tickets__follower_ids f
JOIN zendesk.tickets t ON f._dlt_root_id = t._dlt_id
WHERE t.id = $1
ORDER BY f._dlt_list_idx
`

func (q *Queries) GetTicketFollowers(ctx context.Context, id int64) ([]pgtype.Int8, error) {
	rows, err := q.db.Query(ctx, getTicketFollowers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Int8
	for rows.Next() {
		var value pgtype.Int8
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketFollowups = `-- name: GetTicketFollowups :many
SELECT fu.value FROM zendesk.tickets__followup_ids fu
JOIN zendesk.tickets t ON fu._dlt_root_id = t._dlt_id
WHERE t.id = $1
ORDER BY fu._dlt_list_idx
`

func (q *Queries) GetTicketFollowups(ctx context.Context, id int64) ([]pgtype.Int8, error) {
	rows, err := q.db.Query(ctx, getTicketFollowups, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Int8
	for rows.Next() {
		var value pgtype.Int8
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketTags = `-- name: GetTicketTags :many
SELECT tag.value FROM zendesk.tickets__tags tag
JOIN zendesk.tickets t ON tag._dlt_root_id = t._dlt_id
WHERE t.id = $1
ORDER BY tag._dlt_list_idx
`

func (q *Queries) GetTicketTags(ctx context.Context, id int64) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getTicketTags, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var value pgtype.Text
		if err := rows.Scan(&value); err != nil {
			return nil, err
		}
		items = append(items, value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByCreatedAtAsc = `-- name: ListTicketsByCreatedAtAsc :many
SELECT id, subject, raw_subject, description, status, type, priority, recipient, requester_id, submitter_id, assignee_id, organization_id, group_id, brand_id, ticket_form_id, custom_status_id, external_id, url, created_at, updated_at, generated_timestamp, has_incidents, is_public, allow_channelback, allow_attachments, from_messaging_channel, tags, custom_fields, satisfaction_rating__score, satisfaction_rating__id, satisfaction_rating__reason, satisfaction_rating__reason_id, satisfaction_rating__comment, via__channel, via__source__from, via__source__to, via__source__rel, _dlt_load_id, _dlt_id FROM zendesk.tickets t
WHERE
    ($1::varchar IS NULL OR t.status = $1) AND
    ($2::varchar IS NULL OR t.type = $2) AND
    ($3::varchar IS NULL OR t.priority = $3) AND
    ($4::bigint IS NULL OR t.requester_id = $4) AND
    ($5::bigint IS NULL OR t.assignee_id = $5) AND
    ($6::bigint IS NULL OR t.submitter_id = $6) AND
    ($7::bigint IS NULL OR t.organization_id = $7) AND
    ($8::bigint IS NULL OR t.group_id = $8) AND
    ($9::bigint IS NULL OR t.brand_id = $9) AND
    ($10::varchar IS NULL OR t.subject ILIKE '%' || $10 || '%') AND
    ($11::timestamptz IS NULL OR t.created_at >= $11) AND
    ($12::timestamptz IS NULL OR t.created_at <= $12) AND
    ($13::varchar IS NULL OR EXISTS (
        SELECT 1 FROM zendesk.tickets__tags tag
        WHERE tag._dlt_root_id = t._dlt_id AND tag.value = $13
    ))
ORDER BY t.created_at ASC
LIMIT $15 OFFSET $14
`

type ListTicketsByCreatedAtAscParams struct {
	Status         pgtype.Text
	TicketType     pgtype.Text
	Priority       pgtype.Text
	RequesterID    pgtype.Int8
	AssigneeID     pgtype.Int8
	SubmitterID    pgtype.Int8
	OrganizationID pgtype.Int8
	GroupID        pgtype.Int8
	BrandID        pgtype.Int8
	Search         pgtype.Text
	CreatedAfter   pgtype.Timestamptz
	CreatedBefore  pgtype.Timestamptz
	Tag            pgtype.Text
	QueryOffset    int32
	QueryLimit     int32
}

func (q *Queries) ListTicketsByCreatedAtAsc(ctx context.Context, arg ListTicketsByCreatedAtAscParams) ([]ZendeskTicket, error) {
	rows, err := q.db.Query(ctx, listTicketsByCreatedAtAsc,
		arg.Status,
		arg.TicketType,
		arg.Priority,
		arg.RequesterID,
		arg.AssigneeID,
		arg.SubmitterID,
		arg.OrganizationID,
		arg.GroupID,
		arg.BrandID,
		arg.Search,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.Tag,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZendeskTicket
	for rows.Next() {
		var i ZendeskTicket
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.RawSubject,
			&i.Description,
			&i.Status,
			&i.Type,
			&i.Priority,
			&i.Recipient,
			&i.RequesterID,
			&i.SubmitterID,
			&i.AssigneeID,
			&i.OrganizationID,
			&i.GroupID,
			&i.BrandID,
			&i.TicketFormID,
			&i.CustomStatusID,
			&i.ExternalID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedTimestamp,
			&i.HasIncidents,
			&i.IsPublic,
			&i.AllowChannelback,
			&i.AllowAttachments,
			&i.FromMessagingChannel,
			&i.Tags,
			&i.CustomFields,
			&i.SatisfactionRatingScore,
			&i.SatisfactionRatingID,
			&i.SatisfactionRatingReason,
			&i.SatisfactionRatingReasonID,
			&i.SatisfactionRatingComment,
			&i.ViaChannel,
			&i.ViaSourceFrom,
			&i.ViaSourceTo,
			&i.ViaSourceRel,
			&i.DltLoadID,
			&i.DltID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByCreatedAtDesc = `-- name: ListTicketsByCreatedAtDesc :many
SELECT id, subject, raw_subject, description, status, type, priority, recipient, requester_id, submitter_id, assignee_id, organization_id, group_id, brand_id, ticket_form_id, custom_status_id, external_id, url, created_at, updated_at, generated_timestamp, has_incidents, is_public, allow_channelback, allow_attachments, from_messaging_channel, tags, custom_fields, satisfaction_rating__score, satisfaction_rating__id, satisfaction_rating__reason, satisfaction_rating__reason_id, satisfaction_rating__comment, via__channel, via__source__from, via__source__to, via__source__rel, _dlt_load_id, _dlt_id FROM zendesk.tickets t
WHERE
    ($1::varchar IS NULL OR t.status = $1) AND
    ($2::varchar IS NULL OR t.type = $2) AND
    ($3::varchar IS NULL OR t.priority = $3) AND
    ($4::bigint IS NULL OR t.requester_id = $4) AND
    ($5::bigint IS NULL OR t.assignee_id = $5) AND
    ($6::bigint IS NULL OR t.submitter_id = $6) AND
    ($7::bigint IS NULL OR t.organization_id = $7) AND
    ($8::bigint IS NULL OR t.group_id = $8) AND
    ($9::bigint IS NULL OR t.brand_id = $9) AND
    ($10::varchar IS NULL OR t.subject ILIKE '%' || $10 || '%') AND
    ($11::timestamptz IS NULL OR t.created_at >= $11) AND
    ($12::timestamptz IS NULL OR t.created_at <= $12) AND
    ($13::varchar IS NULL OR EXISTS (
        SELECT 1 FROM zendesk.tickets__tags tag
        WHERE tag._dlt_root_id = t._dlt_id AND tag.value = $13
    ))
ORDER BY t.created_at DESC
LIMIT $15 OFFSET $14
`

type ListTicketsByCreatedAtDescParams struct {
	Status         pgtype.Text
	TicketType     pgtype.Text
	Priority       pgtype.Text
	RequesterID    pgtype.Int8
	AssigneeID     pgtype.Int8
	SubmitterID    pgtype.Int8
	OrganizationID pgtype.Int8
	GroupID        pgtype.Int8
	BrandID        pgtype.Int8
	Search         pgtype.Text
	CreatedAfter   pgtype.Timestamptz
	CreatedBefore  pgtype.Timestamptz
	Tag            pgtype.Text
	QueryOffset    int32
	QueryLimit     int32
}

func (q *Queries) ListTicketsByCreatedAtDesc(ctx context.Context, arg ListTicketsByCreatedAtDescParams) ([]ZendeskTicket, error) {
	rows, err := q.db.Query(ctx, listTicketsByCreatedAtDesc,
		arg.Status,
		arg.TicketType,
		arg.Priority,
		arg.RequesterID,
		arg.AssigneeID,
		arg.SubmitterID,
		arg.OrganizationID,
		arg.GroupID,
		arg.BrandID,
		arg.Search,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.Tag,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZendeskTicket
	for rows.Next() {
		var i ZendeskTicket
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.RawSubject,
			&i.Description,
			&i.Status,
			&i.Type,
			&i.Priority,
			&i.Recipient,
			&i.RequesterID,
			&i.SubmitterID,
			&i.AssigneeID,
			&i.OrganizationID,
			&i.GroupID,
			&i.BrandID,
			&i.TicketFormID,
			&i.CustomStatusID,
			&i.ExternalID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedTimestamp,
			&i.HasIncidents,
			&i.IsPublic,
			&i.AllowChannelback,
			&i.AllowAttachments,
			&i.FromMessagingChannel,
			&i.Tags,
			&i.CustomFields,
			&i.SatisfactionRatingScore,
			&i.SatisfactionRatingID,
			&i.SatisfactionRatingReason,
			&i.SatisfactionRatingReasonID,
			&i.SatisfactionRatingComment,
			&i.ViaChannel,
			&i.ViaSourceFrom,
			&i.ViaSourceTo,
			&i.ViaSourceRel,
			&i.DltLoadID,
			&i.DltID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByUpdatedAtAsc = `-- name: ListTicketsByUpdatedAtAsc :many
SELECT id, subject, raw_subject, description, status, type, priority, recipient, requester_id, submitter_id, assignee_id, organization_id, group_id, brand_id, ticket_form_id, custom_status_id, external_id, url, created_at, updated_at, generated_timestamp, has_incidents, is_public, allow_channelback, allow_attachments, from_messaging_channel, tags, custom_fields, satisfaction_rating__score, satisfaction_rating__id, satisfaction_rating__reason, satisfaction_rating__reason_id, satisfaction_rating__comment, via__channel, via__source__from, via__source__to, via__source__rel, _dlt_load_id, _dlt_id FROM zendesk.tickets t
WHERE
    ($1::varchar IS NULL OR t.status = $1) AND
    ($2::varchar IS NULL OR t.type = $2) AND
    ($3::varchar IS NULL OR t.priority = $3) AND
    ($4::bigint IS NULL OR t.requester_id = $4) AND
    ($5::bigint IS NULL OR t.assignee_id = $5) AND
    ($6::bigint IS NULL OR t.submitter_id = $6) AND
    ($7::bigint IS NULL OR t.organization_id = $7) AND
    ($8::bigint IS NULL OR t.group_id = $8) AND
    ($9::bigint IS NULL OR t.brand_id = $9) AND
    ($10::varchar IS NULL OR t.subject ILIKE '%' || $10 || '%') AND
    ($11::timestamptz IS NULL OR t.created_at >= $11) AND
    ($12::timestamptz IS NULL OR t.created_at <= $12) AND
    ($13::varchar IS NULL OR EXISTS (
        SELECT 1 FROM zendesk.tickets__tags tag
        WHERE tag._dlt_root_id = t._dlt_id AND tag.value = $13
    ))
ORDER BY t.updated_at ASC
LIMIT $15 OFFSET $14
`

type ListTicketsByUpdatedAtAscParams struct {
	Status         pgtype.Text
	TicketType     pgtype.Text
	Priority       pgtype.Text
	RequesterID    pgtype.Int8
	AssigneeID     pgtype.Int8
	SubmitterID    pgtype.Int8
	OrganizationID pgtype.Int8
	GroupID        pgtype.Int8
	BrandID        pgtype.Int8
	Search         pgtype.Text
	CreatedAfter   pgtype.Timestamptz
	CreatedBefore  pgtype.Timestamptz
	Tag            pgtype.Text
	QueryOffset    int32
	QueryLimit     int32
}

func (q *Queries) ListTicketsByUpdatedAtAsc(ctx context.Context, arg ListTicketsByUpdatedAtAscParams) ([]ZendeskTicket, error) {
	rows, err := q.db.Query(ctx, listTicketsByUpdatedAtAsc,
		arg.Status,
		arg.TicketType,
		arg.Priority,
		arg.RequesterID,
		arg.AssigneeID,
		arg.SubmitterID,
		arg.OrganizationID,
		arg.GroupID,
		arg.BrandID,
		arg.Search,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.Tag,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZendeskTicket
	for rows.Next() {
		var i ZendeskTicket
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.RawSubject,
			&i.Description,
			&i.Status,
			&i.Type,
			&i.Priority,
			&i.Recipient,
			&i.RequesterID,
			&i.SubmitterID,
			&i.AssigneeID,
			&i.OrganizationID,
			&i.GroupID,
			&i.BrandID,
			&i.TicketFormID,
			&i.CustomStatusID,
			&i.ExternalID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedTimestamp,
			&i.HasIncidents,
			&i.IsPublic,
			&i.AllowChannelback,
			&i.AllowAttachments,
			&i.FromMessagingChannel,
			&i.Tags,
			&i.CustomFields,
			&i.SatisfactionRatingScore,
			&i.SatisfactionRatingID,
			&i.SatisfactionRatingReason,
			&i.SatisfactionRatingReasonID,
			&i.SatisfactionRatingComment,
			&i.ViaChannel,
			&i.ViaSourceFrom,
			&i.ViaSourceTo,
			&i.ViaSourceRel,
			&i.DltLoadID,
			&i.DltID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByUpdatedAtDesc = `-- name: ListTicketsByUpdatedAtDesc :many
SELECT id, subject, raw_subject, description, status, type, priority, recipient, requester_id, submitter_id, assignee_id, organization_id, group_id, brand_id, ticket_form_id, custom_status_id, external_id, url, created_at, updated_at, generated_timestamp, has_incidents, is_public, allow_channelback, allow_attachments, from_messaging_channel, tags, custom_fields, satisfaction_rating__score, satisfaction_rating__id, satisfaction_rating__reason, satisfaction_rating__reason_id, satisfaction_rating__comment, via__channel, via__source__from, via__source__to, via__source__rel, _dlt_load_id, _dlt_id FROM zendesk.tickets t
WHERE
    ($1::varchar IS NULL OR t.status = $1) AND
    ($2::varchar IS NULL OR t.type = $2) AND
    ($3::varchar IS NULL OR t.priority = $3) AND
    ($4::bigint IS NULL OR t.requester_id = $4) AND
    ($5::bigint IS NULL OR t.assignee_id = $5) AND
    ($6::bigint IS NULL OR t.submitter_id = $6) AND
    ($7::bigint IS NULL OR t.organization_id = $7) AND
    ($8::bigint IS NULL OR t.group_id = $8) AND
    ($9::bigint IS NULL OR t.brand_id = $9) AND
    ($10::varchar IS NULL OR t.subject ILIKE '%' || $10 || '%') AND
    ($11::timestamptz IS NULL OR t.created_at >= $11) AND
    ($12::timestamptz IS NULL OR t.created_at <= $12) AND
    ($13::varchar IS NULL OR EXISTS (
        SELECT 1 FROM zendesk.tickets__tags tag
        WHERE tag._dlt_root_id = t._dlt_id AND tag.value = $13
    ))
ORDER BY t.updated_at DESC
LIMIT $15 OFFSET $14
`

type ListTicketsByUpdatedAtDescParams struct {
	Status         pgtype.Text
	TicketType     pgtype.Text
	Priority       pgtype.Text
	RequesterID    pgtype.Int8
	AssigneeID     pgtype.Int8
	SubmitterID    pgtype.Int8
	OrganizationID pgtype.Int8
	GroupID        pgtype.Int8
	BrandID        pgtype.Int8
	Search         pgtype.Text
	CreatedAfter   pgtype.Timestamptz
	CreatedBefore  pgtype.Timestamptz
	Tag            pgtype.Text
	QueryOffset    int32
	QueryLimit     int32
}

func (q *Queries) ListTicketsByUpdatedAtDesc(ctx context.Context, arg ListTicketsByUpdatedAtDescParams) ([]ZendeskTicket, error) {
	rows, err := q.db.Query(ctx, listTicketsByUpdatedAtDesc,
		arg.Status,
		arg.TicketType,
		arg.Priority,
		arg.RequesterID,
		arg.AssigneeID,
		arg.SubmitterID,
		arg.OrganizationID,
		arg.GroupID,
		arg.BrandID,
		arg.Search,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.Tag,
		arg.QueryOffset,
		arg.QueryLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZendeskTicket
	for rows.Next() {
		var i ZendeskTicket
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.RawSubject,
			&i.Description,
			&i.Status,
			&i.Type,
			&i.Priority,
			&i.Recipient,
			&i.RequesterID,
			&i.SubmitterID,
			&i.AssigneeID,
			&i.OrganizationID,
			&i.GroupID,
			&i.BrandID,
			&i.TicketFormID,
			&i.CustomStatusID,
			&i.ExternalID,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GeneratedTimestamp,
			&i.HasIncidents,
			&i.IsPublic,
			&i.AllowChannelback,
			&i.AllowAttachments,
			&i.FromMessagingChannel,
			&i.Tags,
			&i.CustomFields,
			&i.SatisfactionRatingScore,
			&i.SatisfactionRatingID,
			&i.SatisfactionRatingReason,
			&i.SatisfactionRatingReasonID,
			&i.SatisfactionRatingComment,
			&i.ViaChannel,
			&i.ViaSourceFrom,
			&i.ViaSourceTo,
			&i.ViaSourceRel,
			&i.DltLoadID,
			&i.DltID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
