// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM zendesk.users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, role, organization_id, active, suspended, created_at, updated_at, time_zone, locale, phone, _dlt_load_id, _dlt_id FROM zendesk.users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (ZendeskUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i ZendeskUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.OrganizationID,
		&i.Active,
		&i.Suspended,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeZone,
		&i.Locale,
		&i.Phone,
		&i.DltLoadID,
		&i.DltID,
	)
	return i, err
}

const getUserNames = `-- name: GetUserNames :many
SELECT id, name FROM zendesk.users WHERE id = ANY($1::bigint[])
`

type GetUserNamesRow struct {
	ID   int64
	Name pgtype.Text
}

func (q *Queries) GetUserNames(ctx context.Context, ids []int64) ([]GetUserNamesRow, error) {
	rows, err := q.db.Query(ctx, getUserNames, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserNamesRow
	for rows.Next() {
		var i GetUserNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, role, organization_id, active, suspended, created_at, updated_at, time_zone, locale, phone, _dlt_load_id, _dlt_id FROM zendesk.users
ORDER BY name ASC
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	QueryOffset int32
	QueryLimit  int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ZendeskUser, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.QueryOffset, arg.QueryLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZendeskUser
	for rows.Next() {
		var i ZendeskUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.OrganizationID,
			&i.Active,
			&i.Suspended,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeZone,
			&i.Locale,
			&i.Phone,
			&i.DltLoadID,
			&i.DltID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
